### ISSUE TITLE
Remove the Linktree page (and re-create on website)

### ISSUE THREAD

**Issue by casperdewith** [lipu-tenpo/liputenpo.org#38]
It should not be necessary to have a Linktree page, since we have our own website already.

**Comment by alifeee** [comment]
all links on the linktree should be copied either to:

- a standalone page on the website
- a page like /sona or /lipu-ante

**Comment by alifeee** [comment]
I like the linktree page. It is linked to from many places.

If we were to remove it, we ought to leave it up with a single link to the website, to be backwards compatible.

So, I think we should just leave it as-is.

It provides a good purpose, which is to simply point users towards links. I think it is organised well, and it would be a lot of effort to re-make it on the website to look as good.

I suggest we do not replace it.
