### ISSUE TITLE
Make it look more like the magazine itself

### ISSUE THREAD

**Issue by casperdewith** [lipu-tenpo/liputenpo.org#39]
Currently, the style of the website is very different to that of the magazine. I suggest making them similar. For instance:

- A white background.
- The four-colour scheme.
- The same fonts. (Andika and Bricolage)
- Blobs for the categories and the headers.
   - For each article as well?

**Comment by alifeee** [comment]
fonts are currently

- all fonts are Andika
- headings (h1 h2 h3) are Bricolage
- header is [BogFace](https://github.com/alifeee/bogface). we can change this if you want, but it is a font I made ^.^ 👉👈

**Comment by alifeee** [comment]
> A white background.

I would like the website to be in darkmode. I can add a toggle for lightmode, though.

> The four-colour scheme.

what are the hex codes for these colours and their shades?
