### ISSUE TITLE
Design: make the lipu > toki more distinct

### ISSUE THREAD

**Issue by alifeee** [lipu-tenpo/liputenpo.org#40]
lipu that have toki, have a toki section. e.g., see <https://liputenpo.alifeee.co.uk/lipu/nanpa-sewi/>

I don't think it's very distinct. How could it be better?

![image](https://github.com/lipu-tenpo/liputenpo.org/assets/13833017/ddfda7e3-afaf-4c8a-bdbf-b1b3f56a92fc)

**Comment by ngsilverman** [comment]
It's been changed to:

<img width="514" alt="image" src="https://github.com/lipu-tenpo/liputenpo.org/assets/1723212/583a9051-b95c-4f08-b7e7-3360b423594c">

**Comment by alifeee** [comment]
yep. I think the heading helps make it distinct.

The layout is not perfect, but I am personally happy with it (which is why I stopped...), but would welcome design changes :)

The colours are a bit dissonant, the ordering could be better (same as PDF?). I can't think of much else, as the `toki` are often quite different, so hard to do something like add a preview image/etc, if not all toki would have one.

The former two issues (colour, ordering) deserve their own issues, if considered. So, I'll close this, and those issues can be opened when necessary.  :)
