### ISSUE TITLE
add FAQ item leading to Patreon

### ISSUE THREAD

**Issue by alifeee** [lipu-tenpo/liputenpo.org#61]
Perhaps under "can I get physical copies?"

![image](https://github.com/lipu-tenpo/liputenpo.org/assets/13833017/c3283237-4933-48ab-ba62-f8948e995b0d)

**Comment by ngsilverman** [comment]
This already exists:

<img width="687" alt="image" src="https://github.com/lipu-tenpo/liputenpo.org/assets/1723212/69dab722-b75b-422a-8477-71fb770dc346">

**Comment by gugu256** [comment]
Hi! mi jan Kuku.
I'm willing to contribute to this and add a section right after "What is this" that would look like this:

**Where can I read lipu tenpo?**
You can read lipu tenpo for free on this website, or you can order a physical copy on [our Patreon](https://www.patreon.com/liputenpo/).

**Comment by alifeee** [comment]
> This already exists:

I am happy with this as a link. If you @gugu256 want to modify some FAQ text so it is more clear, then feel free to :)

but I will close this
