### ISSUE TITLE
add licence clarification to footer

### ISSUE THREAD

**Issue by alifeee** [lipu-tenpo/liputenpo.org#68]
something about `CC BY-SA 4.0`.

The footer is here

https://github.com/lipu-tenpo/liputenpo.org/blob/b2d333c68790f39ea65e11fee91c4629453fe427/_includes/page.hbs#L108-L161

**Comment by RetSamys** [comment]
What if there was

`<li><a href="https://creativecommons.org/licenses/by-sa/4.0/"><img class="icon" src="iconns/ccbysa.svg" alt="Creative Commons icon" /><span>nasin jo</span></a></li>`

The icon could be a typical CC BY-SA graphic or an adaptation thereof

**Comment by alifeee** [comment]
I also think just some text under the list would work, like

![image](https://github.com/lipu-tenpo/liputenpo.org/assets/13833017/8c63ab6a-8bae-471b-bd49-883d7d49fa89)

**Comment by jnpoJuwan** [comment]
if I may turn this into a discussion about the footers in general, dividing it up into two columns like so would be ideal I think. as it also would look more professional

![imagem](https://github.com/lipu-tenpo/liputenpo.org/assets/48970145/4e145b8d-29c7-4d83-8369-8b3a5a842e20)

(ignore that this mockup was made in Paint)

**Comment by alifeee** [comment]
> for the design may I suggest forgoing with the weird squiggly lines

You may suggest it, but why? I think that it looks a bit boring with a flat line, so I do not like "it also would look more professional" as a reason.

What do you think of this?

![image](https://github.com/lipu-tenpo/liputenpo.org/assets/13833017/16f76636-beb4-46d4-bb0c-08a1d3b04905)

Here it is on a thin screen (mobile device less than 500px wide)

![image](https://github.com/lipu-tenpo/liputenpo.org/assets/13833017/12df6e9c-a5e4-4590-bef1-967799959916)

Here it is with the squiggle removed

![image](https://github.com/lipu-tenpo/liputenpo.org/assets/13833017/46e6a24c-12ef-4ea3-9bb4-a95c91144268)

**Comment by jnpoJuwan** [comment]
sorry if what I said was not good. this is better but some tweaks are still needed

for desktop try to spread out the links a bit more, comparing the screenshot you sent to the website layout in my screen, there's a big difference

![imagem](https://github.com/lipu-tenpo/liputenpo.org/assets/48970145/df9bc39b-e70e-4d8b-893d-f4230c62c2dd)

for this, put the icons besides the text (and maybe a bit smaller?). besides that, could you move the 'report issues' button (linluwi li pakala → lipu li pakala / pakala li lon) to the right side next to the other info and replace the left side one with the a link to our GitHub
